#import "../../template/template.typ": *

#figure(
  caption: [Expected MACs for Standard\ Transformer Layer (MHA)],
  styled-table(
    columns: (auto, auto, auto),
    inset: 10pt,
    align: horizon,
    table.header([*Operation*], [*MACs Formula*], [*Notes*]),
    [Q Projection],
    [$L dot D^2$],
    [$D times D$ weights],
    [K Projection],
    [$L dot D^2$],
    [$D times D$ weights],
    [V Projection],
    [$L dot D^2$],
    [$D times D$ weights],
    [Attn Scores],
    [$L^2 dot D$],
    [$Q K^T$ (per head sum is $D_h$)],
    [Attn Update],
    [$L^2 dot D$],
    [$A V$ (per head sum is $D_h$)],
    [Output Proj],
    [$L dot D^2$],
    [$D times D$ weights],
    [MLP FFN],
    [$2 dot E dot L dot D^2$],
    [Typically $8 L D^2$ ($E=4$)],
    [*Total*],
    [$approx 12 L D^2 + 2 L^2 D$],
    [Dominated by linear layers],
  ),
) <tab:macs-standard>
