#figure(
  caption: [Expected MACs for Grouped Query Attention Layer (GQA)],
  styled-table(
    columns: (auto, auto, auto),
    inset: 10pt,
    align: horizon,
    table.header([*Operation*], [*MACs Formula*], [*Notes*]),
    [Q Projection],
    [$L dot D^2$],
    [Full Query Heads],
    [K Projection],
    [$L dot D^2 dot (H_("kv")/H_q)$],
    [Reduced Heads],
    [V Projection],
    [$L dot D^2 dot (H_("kv")/H_q)$],
    [Reduced Heads],
    [Attn Scores],
    [$L^2 dot D$],
    [Broadcast K to matching Qs],
    [Attn Update],
    [$L^2 dot D$],
    [Broadcast V to matching Qs],
    [Output Proj],
    [$L dot D^2$],
    [Full Output],
    [MLP FFN],
    [$2 dot E dot L dot D^2$],
    [Standard MLP],
    [*Total*],
    [$approx L D^2 (10 + 2 H_("kv")/H_q) + 2 L^2 D$],
    [Savings in K/V Proj],
  ),
) <tab:macs-gqa>
